export default {
    Narnia: 'Narnia',
    CocoSharp: 'CocoSharp',
    Etalene: 'Etalene',
    MontserratBold: 'MontserratBold',
    MontserratRg: 'MontserratRg',
    PoppinsBlack: 'PoppinsBl',
    PoppinsB: 'PoppinsB',
    PoppinsExtraBold: 'PoppinsExtraBold',
    PoppinsMedium: 'PoppinsMedium',
    PoppinsSemiBold: 'PoppinsSemiBold',
    Ragenik: 'Ragenik',
    RobotoBlack: 'RobotoBlack',
    RobotoMedium: 'RobotoMedium',
    SerifBl: 'SerifBl',
};